// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

import { defineConfig } from "prisma/config";

// Deliberately reads `process.env` rather than `src/config/env.ts`. Two
// reasons: the production image ships only `dist/`, so the TS source is not
// there to import; and a migration should not have to satisfy the full app
// schema (JWT_SECRET, FRONTEND_URL, ...) just to connect to a database.
const url = process.env.DATABASE_URL;

if (!url) {
  throw new Error("DATABASE_URL must be set to run Prisma CLI commands");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url,
  },
});
